version: '3.8'
services:
  db:
    hostname: dbhost
    image: postgres:latest
    container_name: marketplace-postgres
    environment:
      POSTGRES_DB: marketplacedb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: marketplace-nginx
    ports:
      - "8081:80"
    volumes:
      - ./images:/usr/share/nginx/html/images:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  app:
    build: .
    container_name: marketplace-spring-ca
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"
    depends_on:
      - db
    # restart: unless-stopped

# volumes:
#   postgres_data:
